# Python Pandas Cheatsheet

In [27]:
import pandas as pd

## Creating Dataframes

### From dictionary of lists (Column-oriented)

In [28]:
# input data: dict of lists; 1 dict member = 1 column
users_data = {
    'user_id': [101, 102, 103, 104],
    'amount': [250.50, 120.00, None, 450.75],
    'status': ['completed', 'pending', 'failed', 'completed']
}

df = pd.DataFrame(users_data)
df

   user_id  amount     status
0      101  250.50  completed
1      102  120.00    pending
2      103     NaN     failed
3      104  450.75  completed

### From list of dictionaries (Row-oriented)

In [29]:
# input data: list of dicts; 1 dict = 1 row
users_data = [
    {'user_id':101, 'amount':250.50, 'status':'completed'},
    {'user_id':102, 'amount':120.00, 'status':'pending'},
    {'user_id':103, 'amount':None, 'status':'failed'},
    {'user_id':104, 'amount':450.75, 'status':'completed'}
]

df = pd.DataFrame(users_data)
df

   user_id  amount     status
0      101  250.50  completed
1      102  120.00    pending
2      103     NaN     failed
3      104  450.75  completed

### From list of lists (Row-oriented)

In [30]:
# input data: list of lists; 1 list = 1 row
users_data = [
    [101, 250.50, 'completed'],
    [102, 120.00, 'pending'],
    [103, None, 'failed'],
    [104, 450.75, 'completed']
]

# indicate the column names
column_names = ['user_id', 'amount', 'status']

# create the dataframe object
df = pd.DataFrame(users_data, columns=column_names)
df

   user_id  amount     status
0      101  250.50  completed
1      102  120.00    pending
2      103     NaN     failed
3      104  450.75  completed

### From CSV

In [31]:
# Load CSV
df = pd.read_csv('../data/transactions.csv')
df.head()

# Set index column
df = df.set_index('TRANSACTION_ID')
df.head()

,DATE,MERCHANT_ID,TYPE,AMOUNT,STATUS
TRANSACTION_ID,,,,,
981cabf0-9a26-46ab-8d8e-4ac4db2045f0,2021-05-03,93b50990-3dc0-4ec7-bd3e-6e14d4cb4f2e,PURCHASE,852.27,APPROVED
7ecc6848-9e34-4193-9ada-a13413ed8681,2021-05-03,b21431b3-6148-4772-b371-4a086437f427,PURCHASE,365.20,APPROVED
f1e82371-ffd5-4d6e-b24f-0dcc8342be1b,2021-05-03,37795428-a7a7-4441-aafa-f462b1429338,PURCHASE,66.82,APPROVED
8bbee1b7-bd80-4412-b35b-e3579b9c3156,2021-05-03,3e7cbf88-e6cf-4e97-a8a9-5d4117dc9b7b,PURCHASE,299.96,APPROVED
2017bed2-c22c-405e-9ec5-d06011afbbfe,2021-05-03,aa868569-5a49-4db6-8264-e3bf88a1a782,PURCHASE,2.72,APPROVED

## Inspecting Dataframes
Before transforming data, you need to understand its shape, quality, and schema.

### Inspect column names, datatypes, shape

In [32]:
# See column names
df.columns

Index(['DATE', 'MERCHANT_ID', 'TYPE', 'AMOUNT', 'STATUS'], dtype='str')

In [33]:
# See data types per column
df.dtypes

DATE               str
MERCHANT_ID        str
TYPE               str
AMOUNT         float64
STATUS             str
dtype: object

In [34]:
# See shape (number of rows x number of columns)
df.shape

(72234, 5)

### See data snippet

In [35]:
# first x rows
df.head()

,DATE,MERCHANT_ID,TYPE,AMOUNT,STATUS
TRANSACTION_ID,,,,,
981cabf0-9a26-46ab-8d8e-4ac4db2045f0,2021-05-03,93b50990-3dc0-4ec7-bd3e-6e14d4cb4f2e,PURCHASE,852.27,APPROVED
7ecc6848-9e34-4193-9ada-a13413ed8681,2021-05-03,b21431b3-6148-4772-b371-4a086437f427,PURCHASE,365.20,APPROVED
f1e82371-ffd5-4d6e-b24f-0dcc8342be1b,2021-05-03,37795428-a7a7-4441-aafa-f462b1429338,PURCHASE,66.82,APPROVED
8bbee1b7-bd80-4412-b35b-e3579b9c3156,2021-05-03,3e7cbf88-e6cf-4e97-a8a9-5d4117dc9b7b,PURCHASE,299.96,APPROVED
2017bed2-c22c-405e-9ec5-d06011afbbfe,2021-05-03,aa868569-5a49-4db6-8264-e3bf88a1a782,PURCHASE,2.72,APPROVED

In [36]:
# last x rows
df.tail()

,DATE,MERCHANT_ID,TYPE,AMOUNT,STATUS
TRANSACTION_ID,,,,,
e038e47c-9cf0-4ba1-8543-92886913ad01,2022-12-15,ee26d2e0-4d85-4d8e-ae2c-e1d8408a0c75,PURCHASE,70.85,APPROVED
eac4d42b-8218-4a02-843a-ad3c8cd68bd1,2022-12-15,61cbb79e-432f-49c5-9af5-99ca3734bc2e,PURCHASE,4.18,APPROVED
77872197-3da4-493b-9199-9516b6513cca,2022-12-15,1f6363b3-a70a-4322-9fdd-09bf3b6ea8fa,PURCHASE,288.06,PROCESSING
68840a5b-3f73-4831-b8d9-cc77fe527fd3,2022-12-15,c92c63ed-7a69-416f-b3f1-93dfe8c5b97d,PURCHASE,194.47,APPROVED
9c6bde0f-eaef-442e-8900-128c01eca8de,2022-12-15,12dcc78b-6a03-4074-89bb-8e1f43a81c7a,PURCHASE,140.63,APPROVED

### Inspect all details
Quick check for column names, datatypes, null-checking, etc.

In [37]:
df.info()

<class 'pandas.DataFrame'>
Index: 72234 entries, 981cabf0-9a26-46ab-8d8e-4ac4db2045f0 to 9c6bde0f-eaef-442e-8900-128c01eca8de
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE         72234 non-null  str
 1   MERCHANT_ID  72234 non-null  str
 2   TYPE         72234 non-null  str
 3   AMOUNT       72234 non-null  float64
 4   STATUS       72234 non-null  str
dtypes: float64(1), str(4)
memory usage: 3.3+ MB

### Inspect Summary statistics
For numeric columns by default

In [38]:
df.describe()

             AMOUNT
count  72234.000000
mean     254.917137
std      333.337755
min        0.000000
25%       76.960000
50%      154.185000
75%      305.567500
max    10000.000000